version: "2.2"

services:
  proxy:
    image: nginxproxy/nginx-proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/docker/proxy/html:/usr/share/nginx/html
      - ./vhosts:/etc/nginx/vhost.d
      - /srv/docker/letsencrypt/certs:/etc/nginx/certs:ro

  letsencrypt:
    image: nginxproxy/acme-companion:2.0
    container_name: letsencrypt
    restart: always
    depends_on:
      - proxy
    environment:
      - DEFAULT_EMAIL=tann-dev@tann-dev.net
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/docker/letsencrypt/certs:/etc/nginx/certs
      - /srv/docker/letsencrypt/acme.sh:/etc/acme.sh

  postgres:
    image: postgres:13-alpine
    container_name: postgres-13
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    # Do not expose port publicly
    #    ports:
    #      - 5432:5432
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=tann-dev@tann-dev.net
      - PGADMIN_DEFAULT_PASSWORD=univ-smb-m1-isc-2020!
      - VIRTUAL_HOST=pgadmin.tann-dev.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pgadmin.tann-dev.net

################################################
  # Codeshort
  codeshort-backend:
    image: ghcr.io/univ-smb-m1-isc-2022/codeshort-backend/master:latest
    container_name: codeshort-backend
    restart: always
    depends_on:
      - postgres
    environment:
      - VIRTUAL_HOST=codeshort.api.tann-dev.net
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=codeshort.api.tann-dev.net
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/codeshort
      - SPRING_DATASOURCE_USERNAME=codeshort
      - SPRING_DATASOURCE_PASSWORD=codeshort
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./logs:/logs
      - codeshort-backend-resources:/codeshort-backend-resources
      
  codeshort-front:
    image: ghcr.io/univ-smb-m1-isc-2022/codeshort-front/master:latest
    container_name: codeshort-front
    restart: always
    depends_on:
      - codeshort-backend
    environment:
      - VIRTUAL_HOST=codeshort.tann-dev.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=codeshort.tann-dev.net


volumes:
  codeshort-backend-resources: